apiVersion: v1
kind: Secret
metadata:
  name: short-api-secret
  namespace: short-app-namespace
type: Opaque
data:
#  postgres://demo:demo@postgres-cluster-ip:5432/demo
  DATABASE_URL: cG9zdGdyZXM6Ly9kZW1vOmRlbW9AcG9zdGdyZXMtY2x1c3Rlci1pcDo1NDMyL2RlbW8=